stages:
  - test

test_production:
  stage: test
  before_script:
    - eval $(ssh-agent -s)
  script:
    - ssh -o "StrictHostKeyChecking no" -t matthew@92.237.33.217 "cd /home/aston/AstonProject/backend; sh ./testAll.bash;"
  only:
    - "master"
